services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: "postgres"
    restart: always
    shm_size: 120mb
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
